-- Automatically generated by Gerwin
--
-- Project Documentazione
-- From file: /media/picchio/dati/picchio/mondo/scuola/2019-2020/5bit/documenti/manuale.ger
-- By: Picchiottino Roberto per 5bit as 2018-2019
--
-- Using output format: mysql

CREATE DATABASE manuale CHARACTER SET utf8;

GRANT ALL PRIVILEGES ON manuale.*
TO manuale@localhost
IDENTIFIED BY 'manuale'
WITH GRANT OPTION;

-- DROP TABLE esempi; DROP TABLE comandi; DROP TABLE argomenti;

CREATE TABLE argomenti (
      id_argomento     int PRIMARY KEY AUTO_INCREMENT,
      nome     varchar(255),
      descrizione     text,
      id_padre     int NOT NULL
);


INSERT INTO argomenti (nome,descrizione,id_padre) VALUES ("root","radice di tutte le discipline",1);
-- select * from argomenti;


CREATE TABLE comandi (
      id_comando     int PRIMARY KEY AUTO_INCREMENT,
      nome     varchar(255),
      destrizione     text,
      sintassi     text,
      id_argomento     int NOT NULL
);





CREATE TABLE esempi (
      id     int PRIMARY KEY AUTO_INCREMENT,
      testo     text,
      id_comando     int NOT NULL
);



ALTER TABLE argomenti ADD FOREIGN KEY (id_padre) REFERENCES argomenti (id_argomento);


ALTER TABLE comandi ADD FOREIGN KEY (id_argomento) REFERENCES argomenti (id_argomento);


ALTER TABLE esempi ADD FOREIGN KEY (id_comando) REFERENCES comandi (id_comando);


